AllCaptures = {
    "dingo",
    "condor",
    "waterflan",
    "dinonix",
    "killerbee",
    "yellowelement",
    "ragora",
    "miihenfang",
    "ipiria",
    "floatingeye",
    "whiteelement",
    "raldo",
    "vouivre",
    "bomb",
    "dualhorn",
    "raptor",
    "gandarewa",
    "thunderflan",
    "redelement",
    "lamashtu",
    "funguar",
    "garuda",
    "garm",
    "simurgh",
    "bitebug",
    "snowflan",
    "bunyip",
    "basilisk",
    "ochu",
    "melusine",
    "aerouge",
    "buer",
    "goldelement",
    "kusiraqqu",
    "larva",
    "irongiant",
    "quactuar",
    "snowwolf",
    "iguion",
    "wasp",
    "evileye",
    "iceflan",
    "blueelement",
    "murussu",
    "mafdet",
    "xiphos",
    "chimera",
    "sandwolf",
    "alcyone",
    "mushusuu",
    "zu",
    "sandworm",
    "cactuar",
    "skoll",
    "nebiros",
    "flameflan",
    "shred",
    "anacondaur",
    "ogre",
    "coeurl",
    "chimerabrain",
    "malboro",
    "yowie",
    "imp",
    "darkelement",
    "nidhogg",
    "thorn",
    "valaha",
    "epaaj",
    "ghost",
    "tonberry",
    "bandersnatch",
    "ahriman",
    "darkflan",
    "grenade",
    "grat",
    "grendel",
    "bashura",
    "mandragora",
    "behemoth",
    "splasher",
    "achelous",
    "maelspike",
    "exoray",
    "wraith",
    "geminisword",
    "geminiclub",
    "demonolith",
    "greatmalboro",
    "barbatos",
    "adamantoise",
    "behemothking",
    "zaurus",
    "floatingdeath",
    "blackelement",
    "halma",
    "puroboros",
    "spirit",
    "machea",
    "mastercoeurl",
    "mastertonberry",
    "varuna",
}

AllCreations = {
    "stratoavis",
    "malboromenace",
    "kottos",
    "coeurlregina",
    "cactuarking",
    "espada",
    "abyssworm",
    "chimerageist",
    "dontonberry",
    "catoblepas",
    "abaddon",
    "vorban",
    "fenrir",
    "ornitholestes",
    "pteryx",
    "hornet",
    "vidatu",
    "oneeye",
    "jumboflan",
    "negaelemental",
    "tanket",
    "fafnir",
    "sleepsprout",
    "bombking",
    "juggernaut",
    "ironclad",
    "eartheater",
    "greatersphere",
    "catastrophe",
    "thuban",
    "neslug",
    "ultimabuster",
    "shinryu",
}

function CheckAllCaptures(qty)    
    for _, capture in ipairs(AllCaptures) do
        if (Tracker:FindObjectForCode(capture).AcquiredCount < tonumber(qty)) then
            return ACCESS_NONE
        end
    end
    return ACCESS_NORMAL
end

function CheckAllCreations()    
    for _, creation in ipairs(AllCreations) do
        if (not Tracker:FindObjectForCode(creation).Active) then
            return ACCESS_NONE
        end
    end
    return ACCESS_NORMAL
end