Tracker:AddLocations("locations/Spira.json")

Tracker:AddLocations("locations/generic/Al Bhed Primers.json")
Tracker:AddLocations("locations/generic/Blitzball Recruits.json")
Tracker:AddLocations("locations/generic/Celestial.json")
Tracker:AddLocations("locations/generic/Party Member.json")
Tracker:AddLocations("locations/generic/Super Bosses.json")

Tracker:AddLocations("locations/regions/Airship.json")
Tracker:AddLocations("locations/regions/Al Bhed Ship.json")
Tracker:AddLocations("locations/regions/Baaj Temple.json")
Tracker:AddLocations("locations/regions/Besaid.json")
Tracker:AddLocations("locations/regions/Bevelle.json")
Tracker:AddLocations("locations/regions/Bikanel.json")
Tracker:AddLocations("locations/regions/Calm Lands.json")
Tracker:AddLocations("locations/regions/Cavern of the Stolen Fayth.json")
Tracker:AddLocations("locations/regions/Djose.json")
Tracker:AddLocations("locations/regions/Guadosalam.json")
Tracker:AddLocations("locations/regions/Inside Sin.json")
Tracker:AddLocations("locations/regions/Kilika.json")
Tracker:AddLocations("locations/regions/Luca.json")
Tracker:AddLocations("locations/regions/Macalania.json")
Tracker:AddLocations("locations/regions/Miihen Highroad.json")
Tracker:AddLocations("locations/regions/Moonflow.json")
Tracker:AddLocations("locations/regions/Mt. Gagazet.json")
Tracker:AddLocations("locations/regions/Mushroom Rock Road.json")
Tracker:AddLocations("locations/regions/Omega Ruins.json")
Tracker:AddLocations("locations/regions/Remiem Temple.json")
Tracker:AddLocations("locations/regions/S.S. Liki.json")
Tracker:AddLocations("locations/regions/S.S. Winno.json")
Tracker:AddLocations("locations/regions/Thunder Plains.json")
Tracker:AddLocations("locations/regions/Zanarkand.json")

Tracker:AddLocations("locations/monster arena/Monster Arena.json")